### ISSUE TITLE
Move saved models to permanent repository

### ISSUE THREAD

**Issue by agitter** [gitter-lab/metl-pretrained#4]
The saved METL models are current in temporary storage on Box. We need to select a permanent repository and move them there. Options include hosting them on Zenodo, using Hugging Face, or something else.

**Comment by agitter** [comment]
All METL models are now available on Zenodo at https://zenodo.org/doi/10.5281/zenodo.11051644. I will leave this issue open until we convert all of the old Box links to the new Zenodo links.

**Comment by samgelman** [comment]
Completed with d1b9364493917c923365955b4861374d43dce938
